"""empty message

Revision ID: 23f5a49a1ceb
Revises: 
Create Date: 2025-09-13 22:02:59.965405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23f5a49a1ceb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_buttons',
    sa.Column('key', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('menu_key', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('type', sa.String(length=32), server_default=sa.text("'callback'"), nullable=False),
    sa.Column('button_text', sa.String(length=256), nullable=False),
    sa.Column('data', sa.String(length=32), nullable=True),
    sa.Column('order', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key', 'menu_key', 'language')
    )
    op.create_table('interface_messages',
    sa.Column('key', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key', 'language')
    )
    op.create_table('interface_supported_languages',
    sa.Column('lang_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=2), server_default=sa.text("'en'"), nullable=False),
    sa.Column('language_full', sa.String(length=15), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('lang_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('paid_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('payment_reference_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('log_message_history',
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('user_from', sa.BIGINT(), nullable=False),
    sa.Column('user_to', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_message_history')
    op.drop_table('invoices')
    op.drop_table('users')
    op.drop_table('interface_supported_languages')
    op.drop_table('interface_messages')
    op.drop_table('interface_buttons')
    # ### end Alembic commands ###
