"""empty message

Revision ID: 51a362c6ad8e
Revises: 58ee286ce392
Create Date: 2025-04-15 13:00:20.589465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a362c6ad8e'
down_revision: Union[str, None] = '58ee286ce392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_buttons', 'callback_data')
    op.drop_column('interface_buttons', 'web_app_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_buttons', sa.Column('web_app_link', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('interface_buttons', sa.Column('callback_data', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
