"""empty message

Revision ID: 58ee286ce392
Revises: c59d8279a2a6
Create Date: 2025-04-15 12:58:35.929171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ee286ce392'
down_revision: Union[str, None] = 'c59d8279a2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_buttons', sa.Column('type', sa.String(length=32), server_default=sa.text("'callback'"), nullable=False))
    op.add_column('interface_buttons', sa.Column('data', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_buttons', 'data')
    op.drop_column('interface_buttons', 'type')
    # ### end Alembic commands ###
